site_name: "WhisperTrack Docs"
docs_dir: "docs"
theme:
  name: material
  custom_dir: "overrides"
  palette:
    primary: blue
  features:
    - navigation.tabs
    - content.code.copy
    - toc.follow
  logo: "assets/images/popoto/popoto-logo-single-color-white.svg"
extra_css:
  - assets/css/hide-nav-title.css
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - pymdownx.superfences
plugins:
  - search
  - awesome-nav
  - mkdocs-pdf
  - external-markdown
  - mkdocs-video
extra:
  generator: false
extra:
  social:
    - icon: popoto/popoto-logo-blue-with-text
      link: https://www.popotomodem.com/
