nav:
    - Home: 
        - index.md
    - WhisperTrack Overview:
        - how-whispertrack-works.md
    - Software:
        - software/getting-started-with-software.md
        - software/*
    - Hardware:
        - hardware/*
    - "*"
ignore:
    - software/open-standard.md