on:
  push:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: squidfunk/mkdocs-material
      volumes:
        - ${{ github.workspace }}:/docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: mkdocs build
      - name: Upload site folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Set up Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4